version: '3'
services:
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: musa
      LANG: ja_JP.utf8
    ports: 
      - 5432:5432
    volumes:
      - ./docker/postgres/data:/var/lib/postgres/data
    container_name: postgres
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - ./docker/redis/data:/data
    container_name: redis
  rust:
    build:
      context: .
    environment:
      USER: root
    volumes:
      - ./:/musa_diesel
    depends_on:
      - postgres 
      - redis
    links:
      - postgres
      - redis
    container_name: rust

