CREATE TABLE tokens (
  id INTEGER AUTO_INCREMENT PRIMARY KEY,
  access_token TEXT NOT NULL,
  refresh_token TEXT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE sessions (
  id INTEGER AUTO_INCREMENT PRIMARY KEY,
  session_id INTEGER NOT NULL,
  token_id INTEGER NOT NULL,
  last_access DATETIME NOT NULL,
  FOREIGN KEY (token_id)
  REFERENCES tokens(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
